### PR TITLE
Added tested gdew075z09

### PR DESCRIPTION
**Pull request by adrien3d**
I have a gdew075z09 3 color (red) display, that I tested with a new class derived from gdew0583z21.

### CODE REVIEW

**Comment by adrien3d** [comment]
@martinberlin any thoughts on this?

**Comment by adrien3d** [comment]
@martinberlin should you need any proof of work, here you are:

**Comment by martinberlin** [comment]
Great. Thanks for your collaboration.
Merging this. Only request only if you have time, can you take an additional photo with white background so I add this to the Wiki?

**Comment by martinberlin** [comment]
gdew075z09
Adding temporary image for WiKi  https://github.com/martinberlin/cale-idf/wiki/Model-color-gdew075z09.h

**Pull request merged**
